In [183]:
import pandas as pd
import numpy as np
import datetime as dt
from pathlib import Path
%matplotlib inline

In [184]:
# Reading the csv Files with Diseases Data

file_path_E = Path("../../Resources/Data/SPY_Sectors_Ebola_AM.csv")
file_path_H = Path("../../Resources/Data/SPY_Sectors_H1N1_AM.csv")
file_path_S = Path("../../Resources/Data/SPY_Sectors_SARS_AM.csv")
file_path_Z = Path("../../Resources/Data/SPY_Sectors_Zika_AM.csv")

EBOLA_spy_data = pd.read_csv(file_path_E)
H1N1_spy_data = pd.read_csv(file_path_H)
SARS_spy_data = pd.read_csv(file_path_S)
ZIKA_spy_data = pd.read_csv(file_path_Z)

EBOLA_spy_data["Date"]=pd.to_datetime(EBOLA_spy_data["Date"])
ZIKA_spy_data["Date"]=pd.to_datetime(ZIKA_spy_data["Date"])
H1N1_spy_data["Date"]=pd.to_datetime(H1N1_spy_data["Date"])
SARS_spy_data["Date"]=pd.to_datetime(SARS_spy_data["Date"])

# Add a virus name column to each of these dataframes

SARS_spy_data['Disease']='SARS'
H1N1_spy_data['Disease']='H1N1'
EBOLA_spy_data['Disease']='EBOLA'
ZIKA_spy_data['Disease']='ZIKA'

# Concatenate the dataframes together

SP500_data = pd.concat([SARS_spy_data,EBOLA_spy_data,H1N1_spy_data,ZIKA_spy_data], axis=0, join="inner", sort=False).set_index(['Disease','Date'])

SP500_data.head()

                    SP500_Open  SP500_High  SP500_Low  SP500_Close  \
Disease Date
SARS    2003-03-12      799.89      804.19     788.90       804.19
        2003-03-13      806.48      832.02     806.48       831.90
        2003-03-14      831.89      841.39     828.26       833.27
        2003-03-17      832.09      862.79     827.17       862.79
        2003-03-18      862.78      866.94     857.36       866.45

                    SP500_Volume  XLC_Open  XLC_High  XLC_Low  XLC_Close  \
Disease Date
SARS    2003-03-12   162000000.0       0.0       0.0      0.0        0.0
        2003-03-13   181630000.0       0.0       0.0      0.0        0.0
        2003-03-14   154190000.0       0.0       0.0      0.0        0.0
        2003-03-17   170042000.0       0.0       0.0      0.0        0.0
        2003-03-18   155510000.0       0.0       0.0      0.0        0.0

                    XLC_Volume  ...  XLK_Open  XLK_High  XLK_Low  XLK_Close  \
Disease Date                    ...
SARS    2003-03-12         0.0  ...     13.62     13.85    13.42      13.82
        2003-03-13         0.0  ...     14.15     14.59    13.95      14.56
        2003-03-14         0.0  ...     14.70     14.80    14.43      14.61
        2003-03-17         0.0  ...     14.50     15.29    14.40      15.28
        2003-03-18         0.0  ...     15.38     15.39    15.11      15.35

                    XLK_Volume  XLU_Open  XLU_High  XLU_Low  XLU_Close  \
Disease Date
SARS    2003-03-12    442000.0     17.57     17.70    17.39      17.53
        2003-03-13   1448600.0     17.80     17.94    17.60      17.84
        2003-03-14   1418300.0     17.94     18.04    17.81      17.91
        2003-03-17   2986700.0     18.00     18.32    17.89      18.31
        2003-03-18   1443700.0     18.35     18.54    18.26      18.52

                    XLU_Volume
Disease Date
SARS    2003-03-12    273300.0
        2003-03-13    429200.0
        2003-03-14    422600.0
        2003-03-17    460300.0
        2003-03-18    522300.0

[5 rows x 60 columns]

In [185]:
# DataFrames with %Change per Disease

SP500_Sectors_ZIKA = SP500_data.loc['ZIKA',('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume')].pct_change().abs()
SP500_Sectors_H1N1 = SP500_data.loc['H1N1',('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume')].pct_change().abs()
SP500_Sectors_SARS = SP500_data.loc['SARS',('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume')].pct_change().abs()
SP500_Sectors_EBOLA = SP500_data.loc['EBOLA',('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume')].pct_change().abs()

SP500_Sectors_EBOLA.head(10)

,SP500_Close,SP500_Volume,XLY_Close,XLY_Volume,XLP_Close,XLP_Volume,XLE_Close,XLE_Volume,XLF_Close,XLF_Volume,XLV_Close,XLV_Volume,XLI_Close,XLI_Volume,XLB_Close,XLB_Volume,XLK_Close,XLK_Volume,XLU_Close,XLU_Volume
Date,,,,,,,,,,,,,,,,,,,,
2014-03-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-03-04,0.015268,0.092249,0.012536,0.493464,0.013533,0.176031,0.010908,0.155584,0.020595,0.006726,0.018983,0.082851,0.014504,0.286627,0.015755,0.247576,0.013070,0.285536,0.007241,0.316173
2014-03-05,0.000053,0.114554,0.004177,0.723521,0.003279,0.112081,0.009314,0.032389,0.010650,0.045532,0.002495,0.111952,0.001334,0.108897,0.002306,0.468034,0.001372,0.230430,0.006693,0.072018
2014-03-06,0.001718,0.034205,0.002525,0.305599,0.000235,0.240391,0.007223,0.283200,0.002773,0.089305,0.006170,0.322773,0.005711,0.144137,0.003764,0.541315,0.001371,0.029715,0.004991,0.523533
2014-03-07,0.000538,0.003074,0.001482,0.174188,0.002821,0.329109,0.001935,0.265070,0.004978,0.525404,0.002517,0.110968,0.003218,0.352690,0.004375,0.437443,0.003011,0.169408,0.003010,0.003481
2014-03-10,0.000463,0.133373,0.002671,0.245475,0.000938,0.188679,0.001591,0.100306,0.000000,0.643491,0.004205,0.384347,0.004340,0.356888,0.000837,0.462297,0.001647,0.050056,0.002501,0.204748
2014-03-11,0.005082,0.028425,0.005803,0.340698,0.000468,1.043869,0.011343,0.383959,0.006604,0.911774,0.002010,0.224318,0.007201,0.167604,0.010262,0.368360,0.002200,0.251265,0.002758,0.278889
2014-03-12,0.000305,0.014408,0.001497,0.090261,0.002109,0.480539,0.000115,0.236336,0.001662,0.292542,0.000168,0.462734,0.001909,0.298431,0.000423,0.195888,0.001654,0.327869,0.012569,0.015522
2014-03-13,0.011701,0.140977,0.012140,1.354203,0.004910,0.871549,0.009980,0.203246,0.011099,0.783256,0.013597,0.422630,0.014152,0.425655,0.007197,0.482480,0.013484,0.478490,0.010427,1.748623
2014-03-14,0.002822,0.041485,0.000910,0.575260,0.000470,0.455836,0.000927,0.054948,0.006734,0.223661,0.005446,0.362136,0.003880,0.033731,0.000000,0.207839,0.006137,0.048696,0.004668,0.402054

In [186]:
#Calculate Limits-Points per Disease to classify Volatility

#ZIKA
min_ZIKA_data = pd.DataFrame(SP500_Sectors_ZIKA.min()).transpose()
max_ZIKA_data = pd.DataFrame(SP500_Sectors_ZIKA.max()).transpose()
mean_ZIKA_data = pd.DataFrame(SP500_Sectors_ZIKA.mean()).transpose()
aux_df_ZIKA = pd.concat([min_ZIKA_data, max_ZIKA_data, mean_ZIKA_data], axis=0, join="inner", sort=False)
aux_df_ZIKA ['min/max/mean'] = ['min','max','mean']
aux_df_ZIKA ['Disease'] = 'ZIKA'

#H1N1
min_H1N1_data = pd.DataFrame(SP500_Sectors_H1N1.min()).transpose()
max_H1N1_data = pd.DataFrame(SP500_Sectors_H1N1.max()).transpose()
mean_H1N1_data = pd.DataFrame(SP500_Sectors_H1N1.mean()).transpose()
aux_df_H1N1 = pd.concat([min_H1N1_data, max_H1N1_data, mean_H1N1_data], axis=0, join="inner", sort=False)
aux_df_H1N1 ['min/max/mean'] = ['min','max','mean']
aux_df_H1N1 ['Disease'] = 'H1N1'

#SARS
min_SARS_data = pd.DataFrame(SP500_Sectors_SARS.min()).transpose()
max_SARS_data = pd.DataFrame(SP500_Sectors_SARS.max()).transpose()
mean_SARS_data = pd.DataFrame(SP500_Sectors_SARS.mean()).transpose()
aux_df_SARS = pd.concat([min_SARS_data, max_SARS_data, mean_SARS_data], axis=0, join="inner", sort=False)
aux_df_SARS ['min/max/mean'] = ['min','max','mean']
aux_df_SARS ['Disease'] = 'SARS'

#EBOLA
min_EBOLA_data = pd.DataFrame(SP500_Sectors_EBOLA.min()).transpose()
max_EBOLA_data = pd.DataFrame(SP500_Sectors_EBOLA.max()).transpose()
mean_EBOLA_data = pd.DataFrame(SP500_Sectors_EBOLA.mean()).transpose()
aux_df_EBOLA = pd.concat([min_EBOLA_data, max_EBOLA_data, mean_EBOLA_data], axis=0, join="inner", sort=False)
aux_df_EBOLA ['min/max/mean'] = ['min','max','mean']
aux_df_EBOLA ['Disease'] = 'EBOLA'

SP500_Sectors_Change = pd.concat([aux_df_ZIKA, aux_df_H1N1, aux_df_SARS, aux_df_EBOLA], axis=0, join="inner", sort=False).set_index(['Disease','min/max/mean'])

In [187]:
SP500_Sectors_Change

                      SP500_Close  SP500_Volume  XLY_Close  XLY_Volume  \
Disease min/max/mean
ZIKA    min              0.000000      0.000268   0.000000    0.000287
        max              0.039414    197.072109   0.039941    5.820384
        mean             0.005424      0.588873   0.006278    0.332411
H1N1    min              0.000043      0.000004   0.000000    0.002006
        max              0.043974      3.212649   0.052206    2.359725
        mean             0.009246      0.185479   0.011144    0.308462
SARS    min              0.000676      0.001780   0.000000    0.001025
        max              0.035427      0.752583   0.053110   18.306849
        mean             0.009463      0.110712   0.011346    1.736847
EBOLA   min              0.000000      0.000000   0.000000    0.000000
        max              0.039414    197.072109   0.039941    7.355448
        mean             0.004432      0.374401   0.005030    0.282243

                      XLP_Close  XLP_Volume  XLE_Close  XLE_Volume  XLF_Close  \
Disease min/max/mean
ZIKA    min            0.000000    0.000724   0.000129    0.000122   0.000000
        max            0.034794    5.797581   0.053701    3.440648   0.053826
        mean           0.005412    0.364883   0.010469    0.268101   0.007908
H1N1    min            0.000000    0.000630   0.000000    0.000054   0.000000
        max            0.029638    4.401747   0.050185    1.845665   0.111973
        mean           0.006510    0.369295   0.012976    0.271026   0.016045
SARS    min            0.000527    0.005075   0.000000    0.015422   0.000000
        max            0.028633    5.236735   0.029665   21.938926   0.042607
        mean           0.008443    0.990327   0.007947    1.416900   0.010779
EBOLA   min            0.000000    0.000000   0.000000    0.000000   0.000000
        max            0.034794   11.148389   0.064244    3.440648   0.042607
        mean           0.003927    0.319139   0.007613    0.175658   0.005237

                      XLF_Volume  XLV_Close  XLV_Volume  XLI_Close  \
Disease min/max/mean
ZIKA    min             0.001541   0.000000    0.000799   0.000000
        max             3.249247   0.042538    3.989726   0.040748
        mean            0.316095   0.006967    0.344343   0.006338
H1N1    min             0.000940   0.000000    0.001102   0.000000
        max             3.610420   0.031355    2.385883   0.057276
        mean            0.311203   0.007481    0.321213   0.012029
SARS    min             0.003485   0.000000    0.024602   0.000000
        max             7.098212   0.033857   16.285185   0.035471
        mean            0.901826   0.009801    1.530969   0.010194
EBOLA   min             0.000000   0.000000    0.000000   0.000000
        max             3.099161   0.042538    3.989726   0.036728
        mean            0.235677   0.005485    0.234989   0.004960

                      XLI_Volume  XLB_Close  XLB_Volume  XLK_Close  \
Disease min/max/mean
ZIKA    min             0.000287   0.000000    0.001128   0.000000
        max             5.476954   0.043641    4.163256   0.050398
        mean            0.319970   0.007774    0.329938   0.006794
H1N1    min             0.000959   0.000000    0.000088   0.000000
        max             3.757796   0.056354    1.930532   0.045977
        mean            0.322530   0.013736    0.287373   0.009306
SARS    min             0.009479   0.000479    0.040703   0.000000
        max            23.888530   0.044638   21.996350   0.053546
        mean            2.335235   0.010612    2.164820   0.013072
EBOLA   min             0.000000   0.000000    0.000000   0.000000
        max             5.476954   0.041908    4.239962   0.050398
        mean            0.222363   0.005704    0.248020   0.005095

                      XLK_Volume  XLU_Close  XLU_Volume
Disease min/max/mean
ZIKA    min             0.000257   0.000000    0.000205
        max             4.934733   0.037537    2.555824
        mean            0.367712   0.006776    0.312054
H1N1    min             0.000889   0.000000    0.000949
        max             4.480620   0.032126    3.820366
        mean            0.398913   0.008519    0.360246
SARS    min             0.010279   0.000000    0.004048
        max             3.384279   0.037915    3.740814
        mean            0.602929   0.008462    0.456972
EBOLA   min             0.000000   0.000000    0.000000
        max             4.065692   0.041186    2.385995
        mean            0.252720   0.005171    0.223650

In [188]:
print(SP500_Sectors_Change.loc['ZIKA','max']['SP500_Close'])

0.03941366590728046

In [192]:
bins_dict = {'Ticker':'bins'}
for disease in ('ZIKA', 'H1N1', 'SARS', 'EBOLA'):
    for ticker in ('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume'):
        bins_dict[f'{ticker}_{disease}'] = [SP500_Sectors_Change.loc[disease,'min'][ticker], SP500_Sectors_Change.loc[disease,'mean'][ticker], SP500_Sectors_Change.loc[disease,'max'][ticker]]

In [227]:
group_names = ['L', 'H']

# Volatility for Zika
SP500_Sectors_ZIKA.dropna(inplace=True)
for ticker in ('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume'):
    SP500_Sectors_ZIKA[f'V_{ticker}']=pd.cut(SP500_Sectors_ZIKA[ticker], bins_dict[f'{ticker}_ZIKA'],labels=group_names, include_lowest=True)
SP500_Volatility_ZIKA = SP500_Sectors_ZIKA[['V_SP500_Close', 'V_SP500_Volume', 'V_XLY_Close', 'V_XLY_Volume', 'V_XLP_Close', 'V_XLP_Volume', 'V_XLE_Close', 'V_XLE_Volume', 'V_XLF_Close', 'V_XLF_Volume', 'V_XLV_Close', 'V_XLV_Volume', 'V_XLI_Close', 'V_XLI_Volume', 'V_XLB_Close', 'V_XLB_Volume', 'V_XLK_Close', 'V_XLK_Volume', 'V_XLU_Close', 'V_XLU_Volume']]
#SP500_Volatility_ZIKA.head()

# Volatility for H1N1
SP500_Sectors_H1N1.dropna(inplace=True)
for ticker in ('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume'):
    SP500_Sectors_H1N1[f'V_{ticker}']=pd.cut(SP500_Sectors_H1N1[ticker], bins_dict[f'{ticker}_H1N1'],labels=group_names, include_lowest=True)
SP500_Volatility_H1N1 = SP500_Sectors_H1N1[['V_SP500_Close', 'V_SP500_Volume', 'V_XLY_Close', 'V_XLY_Volume', 'V_XLP_Close', 'V_XLP_Volume', 'V_XLE_Close', 'V_XLE_Volume', 'V_XLF_Close', 'V_XLF_Volume', 'V_XLV_Close', 'V_XLV_Volume', 'V_XLI_Close', 'V_XLI_Volume', 'V_XLB_Close', 'V_XLB_Volume', 'V_XLK_Close', 'V_XLK_Volume', 'V_XLU_Close', 'V_XLU_Volume']]
#SP500_Volatility_H1N1.head()

# Volatility for SARS
SP500_Sectors_SARS.dropna(inplace=True)
for ticker in ('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume'):
    SP500_Sectors_SARS[f'V_{ticker}']=pd.cut(SP500_Sectors_SARS[ticker], bins_dict[f'{ticker}_SARS'],labels=group_names, include_lowest=True)
SP500_Volatility_SARS = SP500_Sectors_SARS[['V_SP500_Close', 'V_SP500_Volume', 'V_XLY_Close', 'V_XLY_Volume', 'V_XLP_Close', 'V_XLP_Volume', 'V_XLE_Close', 'V_XLE_Volume', 'V_XLF_Close', 'V_XLF_Volume', 'V_XLV_Close', 'V_XLV_Volume', 'V_XLI_Close', 'V_XLI_Volume', 'V_XLB_Close', 'V_XLB_Volume', 'V_XLK_Close', 'V_XLK_Volume', 'V_XLU_Close', 'V_XLU_Volume']]
SP500_Volatility_SARS.head()

# Volatility for EBOLA
SP500_Sectors_EBOLA.dropna(inplace=True)
for ticker in ('SP500_Close', 'SP500_Volume', 'XLY_Close', 'XLY_Volume', 'XLP_Close', 'XLP_Volume', 'XLE_Close', 'XLE_Volume', 'XLF_Close', 'XLF_Volume', 'XLV_Close', 'XLV_Volume', 'XLI_Close', 'XLI_Volume', 'XLB_Close', 'XLB_Volume', 'XLK_Close', 'XLK_Volume', 'XLU_Close', 'XLU_Volume'):
    SP500_Sectors_EBOLA[f'V_{ticker}']=pd.cut(SP500_Sectors_EBOLA[ticker], bins_dict[f'{ticker}_EBOLA'],labels=group_names, include_lowest=True)
SP500_Volatility_EBOLA = SP500_Sectors_EBOLA[['V_SP500_Close', 'V_SP500_Volume', 'V_XLY_Close', 'V_XLY_Volume', 'V_XLP_Close', 'V_XLP_Volume', 'V_XLE_Close', 'V_XLE_Volume', 'V_XLF_Close', 'V_XLF_Volume', 'V_XLV_Close', 'V_XLV_Volume', 'V_XLI_Close', 'V_XLI_Volume', 'V_XLB_Close', 'V_XLB_Volume', 'V_XLK_Close', 'V_XLK_Volume', 'V_XLU_Close', 'V_XLU_Volume']]
SP500_Volatility_EBOLA.head()

,V_SP500_Close,V_SP500_Volume,V_XLY_Close,V_XLY_Volume,V_XLP_Close,V_XLP_Volume,V_XLE_Close,V_XLE_Volume,V_XLF_Close,V_XLF_Volume,V_XLV_Close,V_XLV_Volume,V_XLI_Close,V_XLI_Volume,V_XLB_Close,V_XLB_Volume,V_XLK_Close,V_XLK_Volume,V_XLU_Close,V_XLU_Volume
Date,,,,,,,,,,,,,,,,,,,,
2014-03-04,H,L,H,H,H,L,H,L,H,L,H,L,H,H,H,L,H,H,H,H
2014-03-05,L,L,L,H,L,L,H,L,H,L,L,L,L,L,L,H,L,L,H,L
2014-03-06,L,L,L,H,L,L,L,H,L,L,H,H,H,L,L,H,L,L,L,H
2014-03-07,L,L,L,L,L,H,L,H,L,H,L,L,L,H,L,H,L,L,L,L
2014-03-10,L,L,L,L,L,L,L,L,L,H,L,H,L,H,L,H,L,L,L,L

In [228]:
SP500_Volatility_SARS.loc[:, 'Disease']='SARS'
SP500_Volatility_H1N1.loc[:, 'Disease']='H1N1'
SP500_Volatility_EBOLA.loc[:, 'Disease']='EBOLA'
SP500_Volatility_ZIKA.loc[:, 'Disease']='ZIKA'
SP500_Volatility_ZIKA.reset_index(inplace=True)
SP500_Volatility_H1N1.reset_index(inplace=True)
SP500_Volatility_SARS.reset_index(inplace=True)
SP500_Volatility_EBOLA.reset_index(inplace=True)

# Concatenate the dataframes together

SP500_Volatility_data = pd.concat([SP500_Volatility_ZIKA, SP500_Volatility_H1N1, SP500_Volatility_SARS, SP500_Volatility_EBOLA], axis=0, join="inner", sort=False).set_index(['Disease','Date'])
SP500_Volatility_data

                   V_SP500_Close V_SP500_Volume V_XLY_Close V_XLY_Volume  \
Disease Date
ZIKA    2015-05-08             H              L           H            L
        2015-05-11             L              L           L            L
        2015-05-12             L              L           L            L
        2015-05-13             L              L           H            L
        2015-05-14             H              L           L            L
...                          ...            ...         ...          ...
EBOLA   2016-03-21             L              L           L            L
        2016-03-22             L              L           L            L
        2016-03-23             L              L           L            L
        2016-03-24             L              L           L            L
        2016-03-28             L              L           L            L

                   V_XLP_Close V_XLP_Volume V_XLE_Close V_XLE_Volume  \
Disease Date
ZIKA    2015-05-08           H            L           H            L
        2015-05-11           L            H           H            L
        2015-05-12           L            L           L            H
        2015-05-13           L            L           L            H
        2015-05-14           H            H           L            L
...                        ...          ...         ...          ...
EBOLA   2016-03-21           L            L           L            L
        2016-03-22           L            L           L            L
        2016-03-23           L            L           L            L
        2016-03-24           L            L           L            L
        2016-03-28           L            L           L            L

                   V_XLF_Close V_XLF_Volume V_XLV_Close V_XLV_Volume  \
Disease Date
ZIKA    2015-05-08           H            L           H            L
        2015-05-11           L            L           L            L
        2015-05-12           L            L           L            L
        2015-05-13           L            H           L            L
        2015-05-14           H            L           H            L
...                        ...          ...         ...          ...
EBOLA   2016-03-21           L            L           L            L
        2016-03-22           L            L           L            L
        2016-03-23           L            L           L            L
        2016-03-24           L            L           L            L
        2016-03-28           L            L           L            L

                   V_XLI_Close V_XLI_Volume V_XLB_Close V_XLB_Volume  \
Disease Date
ZIKA    2015-05-08           H            H           H            L
        2015-05-11           L            L           L            L
        2015-05-12           L            H           H            L
        2015-05-13           L            L           L            L
        2015-05-14           H            L           H            L
...                        ...          ...         ...          ...
EBOLA   2016-03-21           L            L           L            L
        2016-03-22           L            L           L            L
        2016-03-23           L            L           L            L
        2016-03-24           L            L           L            L
        2016-03-28           L            L           L            L

                   V_XLK_Close V_XLK_Volume V_XLU_Close V_XLU_Volume
Disease Date
ZIKA    2015-05-08           H            H           H            L
        2015-05-11           L            H           H            L
        2015-05-12           L            L           L            L
        2015-05-13           L            L           H            L
        2015-05-14           H            L           H            L
...                        ...          ...         ...          ...
EBOLA   2016-03-21           L            L           L            L
        2016-03-22           L            L           L            L
        2016-03-23           L            L           L            L
        2016-03-24           L            L           L            L
        2016-03-28           L            L           L            L

[1788 rows x 20 columns]