In [1]:
# import pandas as pd
# from pathlib import Path
# from iexfinance.refdata import get_symbols

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from iexfinance.stocks import get_historical_data
from iexfinance.refdata import get_symbols
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# ! pip install iexfinance

In [3]:
tickers=pd.DataFrame(get_symbols())
tickers.head()

# get_symbols(output_format='pandas', token= "IEX_SECRET")

,symbol,exchange,name,date,type,iexId,region,currency,isEnabled
0,A,NYS,Agilent Technologies Inc.,2020-02-01,cs,IEX_46574843354B2D52,US,USD,True
1,AA,NYS,Alcoa Corp.,2020-02-01,cs,IEX_4238333734532D52,US,USD,True
2,AAAU,PSE,Perth Mint Physical Gold ETF,2020-02-01,et,IEX_474B433136332D52,US,USD,True
3,AACG,NAS,ATA Creativity Global Sponsored ADR,2020-02-01,ad,IEX_44595A4C53392D52,US,USD,True
4,AADR,PSE,AdvisorShares Dorsey Wright ADR ETF,2020-02-01,et,IEX_5253355435362D52,US,USD,True

In [17]:
# Set the ticker
ticker = "SPY"

# Set start and end datetimes of 1 year, between now and 365 days ago.
# end_date = datetime.now()
end_date = datetime.today()
# start_date = end_date + timedelta(-365)
start_date = end_date + timedelta(-365)

# Get 1 year's worth of historical data for AAPL
df = get_historical_data(ticker, start_date, end_date,  output_format='pandas')
df["ticker"] = ticker
df.head()

              open    high     low   close    volume ticker
date
2019-02-01  270.15  271.20  269.18  270.06  85782524    SPY
2019-02-04  270.11  272.03  269.36  271.96  60744844    SPY
2019-02-05  272.44  273.44  271.88  273.10  79552774    SPY
2019-02-06  272.79  273.34  271.92  272.74  58347791    SPY
2019-02-07  270.94  271.55  268.29  270.14  95481961    SPY

In [18]:
from iexfinance.altdata import get_social_sentiment

In [34]:
# df = get_social_sentiment(ticker, start_date, end_date,  output_format='pandas')
df = get_social_sentiment(ticker, "daily",20200101)
df

{'sentiment': 0.041709270216962524,
 'totalScores': 1521,
 'positive': 0.8,
 'negative': 0.2}